### ISSUE TITLE
Network binding errors

### ISSUE THREAD

**Issue by FallenRiteMonk** [openhab/openhab2#377] opened 2015-09-15 09:38 UTC
Hy @TecSet,

I tested the network binding using the last nights [SNAPSHOT#332](https://openhab.ci.cloudbees.com/job/openHAB2/332/) build on a windows 7 professional 64 bit machine and found following errors: (I have done the tests pinging a virtual machine)
* using system ping it find the machine ON with a pint of ca 2000-3000 ms even if the virtual machine is not on. Using ping in cmd result int not reachable
* with the virtual machine on i get a ping of about 1000-1500 ms not using system ping, a ping of about 30-50 ms using system ping with a actual ping using cmd of 1-6 ms (what is the great problem is the great difference between using and not using system ping from the settings)
* if i use system ping with a refresh rate of 1 sec (to have a rapid update) and then turn then turn of or pause the virtual machine for about a half a minute and then resume it, the network binding starts to rapidly updating for a short wile before returning to normal update rate. In my eyes this must be some how a catching up all the initialized pings that have not resulted in a response but the process but the process was not killed or something like that

I will try to look into these problems my self, but would appreciate some work or help from your side.

Thanks and Greetings,
FallenRiteMonk

**Comment by FallenRiteMonk** [comment] 2015-09-15 10:19
Some logs regarding the errors using system ping, where the network binding was launched, some values where collected, the virtual machine was stopped, some -1 were collected, some strange high ms pings where collected, the virtual machine was continued and then again some "speed up" values where collected:

openhab.log:
```
2015-09-15 12:14:02 [DEBUG] [s.m.i.r.i.ItemRuntimeActivator:23   ] - Registered 'item' configuration parser
2015-09-15 12:14:02 [INFO ] [uartz.impl.StdSchedulerFactory:1184 ] - Using default implementation for ThreadExecutor
2015-09-15 12:14:02 [INFO ] [rtz.core.SchedulerSignalerImpl:61   ] - Initialized Scheduler Signaller of type: class org.quartz.core.SchedulerSignalerImpl
2015-09-15 12:14:02 [INFO ] [rg.quartz.core.QuartzScheduler:240  ] - Quartz Scheduler v.2.2.1 created.
2015-09-15 12:14:02 [INFO ] [org.quartz.simpl.RAMJobStore  :155  ] - RAMJobStore initialized.
2015-09-15 12:14:02 [INFO ] [rg.quartz.core.QuartzScheduler:305  ] - Scheduler meta-data: Quartz Scheduler (v2.2.1) 'openHAB-job-scheduler' with instanceId 'NON_CLUSTERED'
  Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 2 threads.
  Using job-store 'org.quartz.simpl.RAMJobStore' - which does not support persistence. and is not clustered.

2015-09-15 12:14:02 [INFO ] [uartz.impl.StdSchedulerFactory:1339 ] - Quartz scheduler 'openHAB-job-scheduler' initialized from specified file: './runtime/etc/quartz.properties'
2015-09-15 12:14:02 [INFO ] [uartz.impl.StdSchedulerFactory:1343 ] - Quartz scheduler version: 2.2.1
2015-09-15 12:14:02 [DEBUG] [.i.PersistenceRuntimeActivator:23   ] - Registered 'persistence' configuration parser
2015-09-15 12:14:03 [DEBUG] [s.m.r.r.i.RuleRuntimeActivator:35   ] - Registered 'rule' configuration parser
2015-09-15 12:14:03 [DEBUG] [m.s.r.i.ScriptRuntimeActivator:22   ] - Registered 'script' configuration parser
2015-09-15 12:14:03 [DEBUG] [.s.r.i.SitemapRuntimeActivator:23   ] - Registered 'sitemap' configuration parser
2015-09-15 12:14:03 [DEBUG] [.m.t.r.i.ThingRuntimeActivator:23   ] - Registered 'thing' configuration parser
2015-09-15 12:14:04 [DEBUG] [.core.common.ThreadPoolManager:141  ] - Created scheduled thread pool 'discovery' of size 5
2015-09-15 12:14:04 [WARN ] [.j.s.handler.RequestLogHandler:137  ] - !RequestLog
2015-09-15 12:14:05 [DEBUG] [.c.d.internal.ConfigDispatcher:222  ] - Processing config file 'services.cfg'
2015-09-15 12:14:05 [DEBUG] [.c.d.internal.ConfigDispatcher:222  ] - Processing config file 'anel.cfg'
2015-09-15 12:14:05 [DEBUG] [.c.d.internal.ConfigDispatcher:222  ] - Processing config file 'runtime.cfg'
2015-09-15 12:14:05 [DEBUG] [.s.core.internal.CoreActivator:30   ] - Core bundle has been started.
2015-09-15 12:14:05 [DEBUG] [.core.common.ThreadPoolManager:104  ] - Updated scheduled thread pool 'discovery' to size 3
2015-09-15 12:14:05 [DEBUG] [.e.s.c.a.i.AutoUpdateActivator:29   ] - AutoUpdate binding has been started.
2015-09-15 12:14:05 [DEBUG] [c.x.o.XmlDocumentBundleTracker:118  ] - Reading the XML document '/ESH-INF/binding/binding.xml' in module 'org.openhab.binding.network'...
2015-09-15 12:14:05 [DEBUG] [o.e.s.c.s.i.SchedulerActivator:34   ] - Scheduler has been started.
2015-09-15 12:14:05 [INFO ] [rg.quartz.core.QuartzScheduler:575  ] - Scheduler openHAB-job-scheduler_$_NON_CLUSTERED started.
2015-09-15 12:14:05 [DEBUG] [c.x.o.XmlDocumentBundleTracker:159  ] - Create an empty XmlDocumentProvider for the module 'org.openhab.binding.network'.
2015-09-15 12:14:05 [DEBUG] [c.x.o.XmlDocumentBundleTracker:118  ] - Reading the XML document '/ESH-INF/thing/thing-types.xml' in module 'org.openhab.binding.network'...
2015-09-15 12:14:05 [DEBUG] [.c.t.i.TransformationActivator:34   ] - Transformation Service has been started.
2015-09-15 12:14:05 [DEBUG] [c.x.o.XmlDocumentBundleTracker:159  ] - Create an empty XmlDocumentProvider for the module 'org.openhab.binding.network'.
2015-09-15 12:14:06 [DEBUG] [.e.s.i.m.i.MultimediaActivator:32   ] - Multimedia I/O bundle has been started.
2015-09-15 12:14:06 [DEBUG] [io.rest.internal.RESTActivator:32   ] - REST API has been started.
2015-09-15 12:14:06 [DEBUG] [s.i.t.m.internal.MDNSActivator:27   ] - mDNS service has been started.
2015-09-15 12:14:06 [DEBUG] [.i.t.m.internal.MDNSClientImpl:37   ] - mDNS service has been started
2015-09-15 12:14:06 [DEBUG] [i.t.m.internal.MDNSServiceImpl:85   ] - Registering new service _openhab-server._tcp.local. at port 8080
2015-09-15 12:14:06 [DEBUG] [i.t.m.internal.MDNSServiceImpl:85   ] - Registering new service _openhab-server-ssl._tcp.local. at port 8443
2015-09-15 12:14:06 [DEBUG] [.i.r.sse.internal.SseActivator:46   ] - SSE API - SseFeature registered.
2015-09-15 12:14:06 [DEBUG] [.i.r.sse.internal.SseActivator:55   ] - SSE API has been started.
2015-09-15 12:14:06 [DEBUG] [.io.transport.mqtt.MqttService:118  ] - Starting MQTT Service...
2015-09-15 12:14:06 [DEBUG] [.s.s.mapdb.MapDbStorageService:50   ] - Opened MapDB file at 'C:\Users\praktikantit.bruneck\Downloads\openHAB-SNAP\distribution-2.0.0-SNAPSHOT-runtime\.\userdata\mapdb\storage.mapdb'.
2015-09-15 12:14:06 [DEBUG] [.c.c.registry.AbstractRegistry:190  ] - Provider 'org.eclipse.smarthome.core.items.ManagedItemProvider' has been added.
2015-09-15 12:14:06 [DEBUG] [.core.common.ThreadPoolManager:171  ] - Created thread pool 'safeCall' with size 3-10
2015-09-15 12:14:06 [DEBUG] [.c.c.registry.AbstractRegistry:190  ] - Provider 'org.eclipse.smarthome.core.thing.ManagedThingProvider' has been added.
2015-09-15 12:14:06 [DEBUG] [.c.thing.internal.ThingManager:549  ] - Thing handler factory 'NetworkHandlerFactory' added
2015-09-15 12:14:06 [DEBUG] [.c.thing.internal.ThingManager:363  ] - Thing 'network:device:10_90_5_74' is tracked by ThingManager.
2015-09-15 12:14:06 [DEBUG] [.c.thing.internal.ThingManager:487  ] - Calling registerHandler handler for thing 'network:device:10_90_5_74' at 'org.openhab.binding.network.internal.NetworkHandlerFactory@6879a4c3'.
2015-09-15 12:14:06 [DEBUG] [.core.common.ThreadPoolManager:141  ] - Created scheduled thread pool 'thingHandler' of size 3
2015-09-15 12:14:06 [DEBUG] [network.handler.NetworkHandler:83   ] - Initializing Network handler.
2015-09-15 12:14:06 [DEBUG] [.c.thing.internal.ThingManager:84   ] - Thing handler for thing 'network:device:10_90_5_74' added.
2015-09-15 12:14:06 [DEBUG] [.c.thing.internal.ThingManager:252  ] - Assigning handler for thing 'network:device:10_90_5_74'.
2015-09-15 12:14:06 [DEBUG] [.c.t.internal.ThingLinkManager:298  ] - Adding linked item 'network_device_10_90_5_74_online' to channel 'network:device:10_90_5_74:online'.
2015-09-15 12:14:06 [DEBUG] [.c.t.internal.ThingLinkManager:298  ] - Adding linked item 'network_device_10_90_5_74_time' to channel 'network:device:10_90_5_74:time'.
2015-09-15 12:14:06 [DEBUG] [.c.c.registry.AbstractRegistry:190  ] - Provider 'org.eclipse.smarthome.core.thing.link.ManagedItemChannelLinkProvider' has been added.
2015-09-15 12:14:06 [DEBUG] [.c.t.internal.ThingLinkManager:309  ] - Assigning linked group item 'network_device_10_90_5_74' to thing 'network:device:10_90_5_74'.
2015-09-15 12:14:06 [DEBUG] [.c.c.registry.AbstractRegistry:190  ] - Provider 'org.eclipse.smarthome.core.thing.link.ManagedItemThingLinkProvider' has been added.
2015-09-15 12:14:07 [DEBUG] [network.service.NetworkService:196  ] - established connection [host '10.90.14.226' port '0' timeout '5000']
2015-09-15 12:14:07 [DEBUG] [ui.internal.chart.ChartServlet:122  ] - Starting up chart servlet at /chart
2015-09-15 12:14:07 [DEBUG] [u.i.chart.DefaultChartProvider:97   ] - Starting up default chart provider.
2015-09-15 12:14:07 [DEBUG] [o.e.s.u.c.i.servlet.CmdServlet:56   ] - Starting up CMD servlet at /classicui/CMD
2015-09-15 12:14:07 [DEBUG] [s.ui.icon.internal.IconServlet:70   ] - Starting up icon servlet at /icon
2015-09-15 12:14:07 [INFO ] [ui.internal.servlet.PaperUIApp:31   ] - Started Paper UI at /ui
2015-09-15 12:14:07 [DEBUG] [e.s.i.t.upnp.UpnpIOServiceImpl:152  ] - Starting UPnP IO service...
2015-09-15 12:14:07 [INFO ] [.u.d.internal.DashboardService:55   ] - Started dashboard at /start
2015-09-15 12:14:08 [DEBUG] [network.service.NetworkService:196  ] - established connection [host '10.90.14.226' port '0' timeout '5000']
2015-09-15 12:14:08 [DEBUG] [.c.c.registry.AbstractRegistry:190  ] - Provider 'org.eclipse.smarthome.model.item.internal.GenericItemProvider' has been added.
2015-09-15 12:14:08 [INFO ] [rg.quartz.core.QuartzScheduler:2311 ] - JobFactory set to: org.eclipse.smarthome.model.rule.runtime.internal.engine.GuiceAwareJobFactory@520d12e4
2015-09-15 12:14:08 [DEBUG] [.m.r.r.i.engine.RuleEngineImpl:96   ] - Started rule engine
2015-09-15 12:14:08 [INFO ] [.s.u.c.i.servlet.WebAppServlet:85   ] - Started Classic UI at /classicui/app
2015-09-15 12:14:08 [DEBUG] [e.s.m.t.i.GenericThingProvider:696  ] - ThingHandlerFactory added org.openhab.binding.network.internal.NetworkHandlerFactory@6879a4c3
2015-09-15 12:14:08 [DEBUG] [.c.c.registry.AbstractRegistry:190  ] - Provider 'org.eclipse.smarthome.model.thing.internal.GenericThingProvider' has been added.
2015-09-15 12:14:09 [DEBUG] [.c.c.registry.AbstractRegistry:190  ] - Provider 'org.eclipse.smarthome.model.thing.internal.GenericItemChannelLinkProvider' has been added.
2015-09-15 12:14:09 [DEBUG] [ui.internal.proxy.ProxyServlet:94   ] - Starting up proxy servlet at /proxy
2015-09-15 12:14:09 [INFO ] [.o.core.internal.CoreActivator:41   ] - openHAB runtime has been started (v2.0.0, build 201509150104).
2015-09-15 12:14:09 [DEBUG] [.o.core.internal.CoreActivator:47   ] - Startup took 12400 ms
2015-09-15 12:14:10 [DEBUG] [network.service.NetworkService:196  ] - established connection [host '10.90.14.226' port '0' timeout '5000']
2015-09-15 12:14:11 [DEBUG] [network.service.NetworkService:196  ] - established connection [host '10.90.14.226' port '0' timeout '5000']
2015-09-15 12:14:12 [DEBUG] [network.service.NetworkService:196  ] - established connection [host '10.90.14.226' port '0' timeout '5000']
2015-09-15 12:14:13 [DEBUG] [network.service.NetworkService:196  ] - established connection [host '10.90.14.226' port '0' timeout '5000']
2015-09-15 12:14:13 [DEBUG] [network.service.NetworkService:196  ] - established connection [host '10.90.14.226' port '0' timeout '5000']
2015-09-15 12:14:13 [DEBUG] [network.service.NetworkService:196  ] - established connection [host '10.90.14.226' port '0' timeout '5000']
2015-09-15 12:14:14 [DEBUG] [network.service.NetworkService:196  ] - established connection [host '10.90.14.226' port '0' timeout '5000']
2015-09-15 12:14:15 [DEBUG] [network.service.NetworkService:196  ] - established connection [host '10.90.14.226' port '0' timeout '5000']
2015-09-15 12:14:21 [DEBUG] [network.service.NetworkService:187  ] - Ping stopped with Error Number: 1 on Command :ping -w 5000 -n 1 10.90.14.226
2015-09-15 12:14:21 [DEBUG] [network.service.NetworkService:196  ] - established connection [host '10.90.14.226' port '0' timeout '5000']
2015-09-15 12:14:26 [DEBUG] [network.service.NetworkService:187  ] - Ping stopped with Error Number: 1 on Command :ping -w 5000 -n 1 10.90.14.226
2015-09-15 12:14:26 [DEBUG] [network.service.NetworkService:196  ] - established connection [host '10.90.14.226' port '0' timeout '5000']
2015-09-15 12:14:31 [DEBUG] [network.service.NetworkService:187  ] - Ping stopped with Error Number: 1 on Command :ping -w 5000 -n 1 10.90.14.226
2015-09-15 12:14:31 [DEBUG] [network.service.NetworkService:196  ] - established connection [host '10.90.14.226' port '0' timeout '5000']
2015-09-15 12:14:36 [DEBUG] [network.service.NetworkService:187  ] - Ping stopped with Error Number: 1 on Command :ping -w 5000 -n 1 10.90.14.226
2015-09-15 12:14:36 [DEBUG] [network.service.NetworkService:196  ] - established connection [host '10.90.14.226' port '0' timeout '5000']
2015-09-15 12:14:41 [DEBUG] [network.service.NetworkService:187  ] - Ping stopped with Error Number: 1 on Command :ping -w 5000 -n 1 10.90.14.226
2015-09-15 12:14:41 [DEBUG] [network.service.NetworkService:196  ] - established connection [host '10.90.14.226' port '0' timeout '5000']
2015-09-15 12:14:44 [DEBUG] [network.service.NetworkService:196  ] - established connection [host '10.90.14.226' port '0' timeout '5000']
2015-09-15 12:14:47 [DEBUG] [network.service.NetworkService:196  ] - established connection [host '10.90.14.226' port '0' timeout '5000']
2015-09-15 12:14:50 [DEBUG] [network.service.NetworkService:196  ] - established connection [host '10.90.14.226' port '0' timeout '5000']
2015-09-15 12:14:50 [DEBUG] [network.service.NetworkService:196  ] - established connection [host '10.90.14.226' port '0' timeout '5000']
2015-09-15 12:14:50 [DEBUG] [network.service.NetworkService:196  ] - established connection [host '10.90.14.226' port '0' timeout '5000']
2015-09-15 12:14:50 [DEBUG] [network.service.NetworkService:196  ] - established connection [host '10.90.14.226' port '0' timeout '5000']
2015-09-15 12:14:50 [DEBUG] [network.service.NetworkService:196  ] - established connection [host '10.90.14.226' port '0' timeout '5000']
2015-09-15 12:14:50 [DEBUG] [network.service.NetworkService:196  ] - established connection [host '10.90.14.226' port '0' timeout '5000']
2015-09-15 12:14:50 [DEBUG] [network.service.NetworkService:196  ] - established connection [host '10.90.14.226' port '0' timeout '5000']
2015-09-15 12:14:50 [DEBUG] [network.service.NetworkService:196  ] - established connection [host '10.90.14.226' port '0' timeout '5000']
2015-09-15 12:14:50 [DEBUG] [network.service.NetworkService:196  ] - established connection [host '10.90.14.226' port '0' timeout '5000']
2015-09-15 12:14:51 [DEBUG] [network.service.NetworkService:196  ] - established connection [host '10.90.14.226' port '0' timeout '5000']
2015-09-15 12:14:51 [DEBUG] [network.service.NetworkService:196  ] - established connection [host '10.90.14.226' port '0' timeout '5000']
2015-09-15 12:14:51 [DEBUG] [network.service.NetworkService:196  ] - established connection [host '10.90.14.226' port '0' timeout '5000']
2015-09-15 12:14:51 [DEBUG] [network.service.NetworkService:196  ] - established connection [host '10.90.14.226' port '0' timeout '5000']
2015-09-15 12:14:51 [DEBUG] [network.service.NetworkService:196  ] - established connection [host '10.90.14.226' port '0' timeout '5000']
2015-09-15 12:14:51 [DEBUG] [network.service.NetworkService:196  ] - established connection [host '10.90.14.226' port '0' timeout '5000']
2015-09-15 12:14:51 [DEBUG] [network.service.NetworkService:196  ] - established connection [host '10.90.14.226' port '0' timeout '5000']
2015-09-15 12:14:51 [DEBUG] [network.service.NetworkService:196  ] - established connection [host '10.90.14.226' port '0' timeout '5000']
2015-09-15 12:14:51 [DEBUG] [network.service.NetworkService:196  ] - established connection [host '10.90.14.226' port '0' timeout '5000']
2015-09-15 12:14:51 [DEBUG] [network.service.NetworkService:196  ] - established connection [host '10.90.14.226' port '0' timeout '5000']
2015-09-15 12:14:51 [DEBUG] [network.service.NetworkService:196  ] - established connection [host '10.90.14.226' port '0' timeout '5000']
2015-09-15 12:14:51 [DEBUG] [network.service.NetworkService:196  ] - established connection [host '10.90.14.226' port '0' timeout '5000']
2015-09-15 12:14:51 [DEBUG] [network.service.NetworkService:196  ] - established connection [host '10.90.14.226' port '0' timeout '5000']
2015-09-15 12:14:51 [DEBUG] [network.service.NetworkService:196  ] - established connection [host '10.90.14.226' port '0' timeout '5000']
2015-09-15 12:14:51 [DEBUG] [network.service.NetworkService:196  ] - established connection [host '10.90.14.226' port '0' timeout '5000']
2015-09-15 12:14:51 [DEBUG] [network.service.NetworkService:196  ] - established connection [host '10.90.14.226' port '0' timeout '5000']
2015-09-15 12:14:51 [DEBUG] [network.service.NetworkService:196  ] - established connection [host '10.90.14.226' port '0' timeout '5000']
2015-09-15 12:14:51 [DEBUG] [network.service.NetworkService:196  ] - established connection [host '10.90.14.226' port '0' timeout '5000']
2015-09-15 12:14:51 [DEBUG] [network.service.NetworkService:196  ] - established connection [host '10.90.14.226' port '0' timeout '5000']
2015-09-15 12:14:51 [DEBUG] [network.service.NetworkService:196  ] - established connection [host '10.90.14.226' port '0' timeout '5000']
2015-09-15 12:14:52 [DEBUG] [network.service.NetworkService:196  ] - established connection [host '10.90.14.226' port '0' timeout '5000']
2015-09-15 12:14:53 [DEBUG] [network.service.NetworkService:196  ] - established connection [host '10.90.14.226' port '0' timeout '5000']
2015-09-15 12:14:54 [DEBUG] [network.service.NetworkService:196  ] - established connection [host '10.90.14.226' port '0' timeout '5000']
2015-09-15 12:14:55 [DEBUG] [network.service.NetworkService:196  ] - established connection [host '10.90.14.226' port '0' timeout '5000']
2015-09-15 12:14:56 [INFO ] [ui.internal.servlet.PaperUIApp:39   ] - Stopped Paper UI
2015-09-15 12:14:56 [INFO ] [.u.d.internal.DashboardService:63   ] - Stopped dashboard
2015-09-15 12:14:56 [INFO ] [.s.u.c.i.servlet.WebAppServlet:103  ] - Stopped Classic UI
```

events.log:
```
2015-09-15 12:14:06 - Item 'home_group_84685f17' has been added.
2015-09-15 12:14:06 - Item 'network_device_10_90_5_74' has been added.
2015-09-15 12:14:06 - Item 'network_device_10_90_5_74_online' has been added.
2015-09-15 12:14:06 - Item 'network_device_10_90_5_74_time' has been added.
2015-09-15 12:14:06 - Thing 'network:device:10_90_5_74' has been added.
2015-09-15 12:14:06 - network:device:10_90_5_74' updated: INITIALIZING
2015-09-15 12:14:06 - network:device:10_90_5_74' updated: ONLINE
2015-09-15 12:14:07 - network_device_10_90_5_74_online updated to ON
2015-09-15 12:14:07 - network_device_10_90_5_74_time updated to 77.3717840000000052214090828783810138702392578125
2015-09-15 12:14:08 - network_device_10_90_5_74_online updated to ON
2015-09-15 12:14:08 - network_device_10_90_5_74_time updated to 268.643330999999989217030815780162811279296875
2015-09-15 12:14:10 - network_device_10_90_5_74_online updated to ON
2015-09-15 12:14:10 - network_device_10_90_5_74_time updated to 1922.021343999999999141437001526355743408203125
2015-09-15 12:14:11 - network_device_10_90_5_74_online updated to ON
2015-09-15 12:14:11 - network_device_10_90_5_74_time updated to 1087.75290799999993396340869367122650146484375
2015-09-15 12:14:12 - network_device_10_90_5_74_online updated to ON
2015-09-15 12:14:12 - network_device_10_90_5_74_time updated to 877.0123800000000073850969783961772918701171875
2015-09-15 12:14:13 - network_device_10_90_5_74_online updated to ON
2015-09-15 12:14:13 - network_device_10_90_5_74_time updated to 184.8843630000000075597199611365795135498046875
2015-09-15 12:14:13 - network_device_10_90_5_74_online updated to ON
2015-09-15 12:14:13 - network_device_10_90_5_74_time updated to 75.7825030000000054997144616208970546722412109375
2015-09-15 12:14:13 - network_device_10_90_5_74_online updated to ON
2015-09-15 12:14:13 - network_device_10_90_5_74_time updated to 40.27155900000000343652573064900934696197509765625
2015-09-15 12:14:14 - network_device_10_90_5_74_online updated to ON
2015-09-15 12:14:14 - network_device_10_90_5_74_time updated to 36.38872099999999676356310374103486537933349609375
2015-09-15 12:14:15 - network_device_10_90_5_74_online updated to ON
2015-09-15 12:14:15 - network_device_10_90_5_74_time updated to 54.92209199999999924557414487935602664947509765625
2015-09-15 12:14:21 - network_device_10_90_5_74_online updated to OFF
2015-09-15 12:14:21 - network_device_10_90_5_74_time updated to -1
2015-09-15 12:14:26 - network_device_10_90_5_74_online updated to OFF
2015-09-15 12:14:26 - network_device_10_90_5_74_time updated to -1
2015-09-15 12:14:31 - network_device_10_90_5_74_online updated to OFF
2015-09-15 12:14:31 - network_device_10_90_5_74_time updated to -1
2015-09-15 12:14:36 - network_device_10_90_5_74_online updated to OFF
2015-09-15 12:14:36 - network_device_10_90_5_74_time updated to -1
2015-09-15 12:14:41 - network_device_10_90_5_74_online updated to OFF
2015-09-15 12:14:41 - network_device_10_90_5_74_time updated to -1
2015-09-15 12:14:44 - network_device_10_90_5_74_online updated to ON
2015-09-15 12:14:44 - network_device_10_90_5_74_time updated to 2994.12875200000007680500857532024383544921875
2015-09-15 12:14:47 - network_device_10_90_5_74_online updated to ON
2015-09-15 12:14:47 - network_device_10_90_5_74_time updated to 2993.0261110000001281150616705417633056640625
2015-09-15 12:14:50 - network_device_10_90_5_74_online updated to ON
2015-09-15 12:14:50 - network_device_10_90_5_74_time updated to 2997.388738999999986845068633556365966796875
2015-09-15 12:14:50 - network_device_10_90_5_74_online updated to ON
2015-09-15 12:14:50 - network_device_10_90_5_74_time updated to 52.37056700000000120098775369115173816680908203125
2015-09-15 12:14:50 - network_device_10_90_5_74_online updated to ON
2015-09-15 12:14:50 - network_device_10_90_5_74_time updated to 36.56031800000000231420926866121590137481689453125
2015-09-15 12:14:50 - network_device_10_90_5_74_online updated to ON
2015-09-15 12:14:50 - network_device_10_90_5_74_time updated to 49.46861700000000183763404493220150470733642578125
2015-09-15 12:14:50 - network_device_10_90_5_74_online updated to ON
2015-09-15 12:14:50 - network_device_10_90_5_74_time updated to 40.58127300000000303725755657069385051727294921875
2015-09-15 12:14:50 - network_device_10_90_5_74_online updated to ON
2015-09-15 12:14:50 - network_device_10_90_5_74_time updated to 34.198273999999997840859577991068363189697265625
2015-09-15 12:14:50 - network_device_10_90_5_74_online updated to ON
2015-09-15 12:14:50 - network_device_10_90_5_74_time updated to 36.15966900000000094905772130005061626434326171875
2015-09-15 12:14:50 - network_device_10_90_5_74_online updated to ON
2015-09-15 12:14:50 - network_device_10_90_5_74_time updated to 35.20846000000000231011654250323772430419921875
2015-09-15 12:14:50 - network_device_10_90_5_74_online updated to ON
2015-09-15 12:14:50 - network_device_10_90_5_74_time updated to 35.91121299999999649799065082333981990814208984375
2015-09-15 12:14:51 - network_device_10_90_5_74_online updated to ON
2015-09-15 12:14:51 - network_device_10_90_5_74_time updated to 36.3114819999999980382199282757937908172607421875
2015-09-15 12:14:51 - network_device_10_90_5_74_online updated to ON
2015-09-15 12:14:51 - network_device_10_90_5_74_time updated to 37.22882899999999750662027508951723575592041015625
2015-09-15 12:14:51 - network_device_10_90_5_74_online updated to ON
2015-09-15 12:14:51 - network_device_10_90_5_74_time updated to 40.48919599999999974215825204737484455108642578125
2015-09-15 12:14:51 - network_device_10_90_5_74_online updated to ON
2015-09-15 12:14:51 - network_device_10_90_5_74_time updated to 36.65581999999999851524989935569465160369873046875
2015-09-15 12:14:51 - network_device_10_90_5_74_online updated to ON
2015-09-15 12:14:51 - network_device_10_90_5_74_time updated to 37.2680179999999978690539137460291385650634765625
2015-09-15 12:14:51 - network_device_10_90_5_74_online updated to ON
2015-09-15 12:14:51 - network_device_10_90_5_74_time updated to 34.59435799999999971987563185393810272216796875
2015-09-15 12:14:51 - network_device_10_90_5_74_online updated to ON
2015-09-15 12:14:51 - network_device_10_90_5_74_time updated to 34.694805999999999812644091434776782989501953125
2015-09-15 12:14:51 - network_device_10_90_5_74_online updated to ON
2015-09-15 12:14:51 - network_device_10_90_5_74_time updated to 38.23026200000000329737304127775132656097412109375
2015-09-15 12:14:51 - network_device_10_90_5_74_online updated to ON
2015-09-15 12:14:51 - network_device_10_90_5_74_time updated to 42.493966000000000349245965480804443359375
2015-09-15 12:14:51 - network_device_10_90_5_74_online updated to ON
2015-09-15 12:14:51 - network_device_10_90_5_74_time updated to 38.55519600000000224326868192292749881744384765625
2015-09-15 12:14:51 - network_device_10_90_5_74_online updated to ON
2015-09-15 12:14:51 - network_device_10_90_5_74_time updated to 33.929653000000001838998286984860897064208984375
2015-09-15 12:14:51 - network_device_10_90_5_74_online updated to ON
2015-09-15 12:14:51 - network_device_10_90_5_74_time updated to 35.3028199999999969804775901138782501220703125
2015-09-15 12:14:51 - network_device_10_90_5_74_online updated to ON
2015-09-15 12:14:51 - network_device_10_90_5_74_time updated to 37.7474289999999967903931974433362483978271484375
2015-09-15 12:14:51 - network_device_10_90_5_74_online updated to ON
2015-09-15 12:14:51 - network_device_10_90_5_74_time updated to 35.87354599999999749115886515937745571136474609375
2015-09-15 12:14:51 - network_device_10_90_5_74_online updated to ON
2015-09-15 12:14:51 - network_device_10_90_5_74_time updated to 35.23699599999999776400727569125592708587646484375
2015-09-15 12:14:51 - network_device_10_90_5_74_online updated to ON
2015-09-15 12:14:51 - network_device_10_90_5_74_time updated to 34.99348599999999720466803410090506076812744140625
2015-09-15 12:14:51 - network_device_10_90_5_74_online updated to ON
2015-09-15 12:14:51 - network_device_10_90_5_74_time updated to 35.99682200000000165118763106875121593475341796875
2015-09-15 12:14:51 - network_device_10_90_5_74_online updated to ON
2015-09-15 12:14:51 - network_device_10_90_5_74_time updated to 37.15881999999999862893673707731068134307861328125
2015-09-15 12:14:51 - network_device_10_90_5_74_online updated to ON
2015-09-15 12:14:51 - network_device_10_90_5_74_time updated to 36.1414060000000034733602660708129405975341796875
2015-09-15 12:14:51 - network_device_10_90_5_74_online updated to ON
2015-09-15 12:14:51 - network_device_10_90_5_74_time updated to 62.24869000000000340833139489404857158660888671875
2015-09-15 12:14:52 - network_device_10_90_5_74_online updated to ON
2015-09-15 12:14:52 - network_device_10_90_5_74_time updated to 47.9873919999999998253770172595977783203125
2015-09-15 12:14:53 - network_device_10_90_5_74_online updated to ON
2015-09-15 12:14:53 - network_device_10_90_5_74_time updated to 58.40390099999999762303559691645205020904541015625
2015-09-15 12:14:54 - network_device_10_90_5_74_online updated to ON
2015-09-15 12:14:54 - network_device_10_90_5_74_time updated to 53.935878000000002430169843137264251708984375
2015-09-15 12:14:55 - network_device_10_90_5_74_online updated to ON
2015-09-15 12:14:55 - network_device_10_90_5_74_time updated to 56.161709000000001879016053862869739532470703125
```

hope this helps

**Comment by FallenRiteMonk** [comment] 2015-09-15 14:34
Another error:
* defining a item with the time channel doesn't support a label like "Ping [%.1f ms]". Only a plain decimal number with 6 numbers after the dot gets displayed (exp.: "Ping 11.805319")

**Comment by FallenRiteMonk** [comment] 2015-09-15 14:53
* starting the device discovery never ends, leading to a openHAB state where I can't stop it anymore using CTRL+C as usual (Running it under windows)

@kaikreuzer this might also be interesting for you as i think this might also be a problem in other bindings (I mean the shutting down while a discovery task is running) since I have also notices already several times that this can also lead to some error being thrown (I'm sorry but I haven't got any log for this error)

**Comment by kaikreuzer** [comment] 2015-09-16 14:46
>  i think this might also be a problem in other bindings 

@FallenRiteMonk: You are right, but I am afraid there is no general easy solution for this, since any thread that is started and does not respond on interrupt signals can potentially prevent the shutdown. So the only way is to make sure that the discovery services are implemented nicely. If you come across any blocking services, please submit an issue, so it can be addressed!

**Comment by kaikreuzer** [comment] 2015-10-26 04:50
@TecSet Ay update on this?

**Comment by TecSet** [comment] 2015-10-28 05:20
* if i use system ping with a refresh rate of 1 sec (to have a rapid update) and then turn then turn of or pause the virtual machine for about a half a minute and then resume it, the network binding starts to rapidly updating for a short wile before returning to normal update rate. In my eyes this must be some how a catching up all the initialized pings that have not resulted in a response but the process but the process was not killed or something like that

The problem is the timeout. When the timeout is larger than the refresh_rate, it creates a lot of processes which are running the same time. (timout/refres_rate). When the device is on again, every process will return which leads to an overhead.
--Expected User Error Problem. No fix

* with the virtual machine on i get a ping of about 1000-1500 ms not using system ping, a ping of about 30-50 ms using system ping with a actual ping using cmd of 1-6 ms (what is the great problem is the great difference between using and not using system ping from the settings)

The Problem with using ping and SystemTime in Java is:
--The Java Ping is not the best implementation
--SystemTime is not really correct. 
Using Ping in cmd will always lead to different results, because process time and time fluctuation in Java will always interfere. 

* Defining a item with the time channel doesn't support a label like "Ping [%.1f ms]" in the paperUI. Only a plain decimal number with 6 numbers after the dot gets displayed (exp.: "Ping 11.805319")
* The classicUI doesn't show any value at all for a item of time channel

Redirecting to PaperUI - no NetworkBinding Error

**Comment by kaikreuzer** [comment] 2015-10-28 13:27
Thanks for the update, so I am closing this as won't fix.

**Closed by kaikreuzer** 2015-10-28 13:27 UTC
