### ISSUE TITLE
No icons: unsatisfied components

### ISSUE THREAD

**Issue by SuperOok** [openhab/openhab2#529] opened 2015-12-07 21:59 UTC
I'm testing the latest Build [#435](https://openhab.ci.cloudbees.com/job/openHAB2/435/), runtime demo.
It seems to work but does not show any icons.

There are two components unsatisfied:
```
52      Unsatisfied             org.eclipse.smarthome.cors                      org.eclipse.smarthome.io.rest(bid=99)
58      Unsatisfied             org.eclipse.smarthome.io.rest.core.binding.ExtensionResource                    org.eclipse.smarthome.io.rest.core(bid=100)

comp 52
        Component[
        name = org.eclipse.smarthome.cors
        activate = activate
        deactivate = deactivate
        modified =
        configuration-policy = require
        factory = null
        autoenable = true
        immediate = true
        implementation = org.eclipse.smarthome.io.rest.internal.filter.CorsFilter
        state = Unsatisfied
        properties = {service.pid=org.eclipse.smarthome.cors}
        serviceFactory = false
        serviceInterface = [javax.ws.rs.container.ContainerResponseFilter]
        references = null
        located in bundle = org.eclipse.smarthome.io.rest_0.8.0.201512041029 [99]
]
Dynamic information :
  The component is satisfied
  All component references are satisfied
  Component configurations :
  *The component has NO built configurations! The reason might be that it requires initialization by configuration provided by Configuration Admin but none was found

osgi> comp 58
        Component[
        name = org.eclipse.smarthome.io.rest.core.binding.ExtensionResource
        activate = activate
        deactivate = deactivate
        modified =
        configuration-policy = optional
        factory = null
        autoenable = true
        immediate = true
        implementation = org.eclipse.smarthome.io.rest.core.extensions.ExtensionResource
        state = Unsatisfied
        properties =
        serviceFactory = false
        serviceInterface = [org.eclipse.smarthome.io.rest.RESTResource, org.eclipse.smarthome.io.rest.core.extensions.ExtensionResource]
        references = {
                Reference[name = ExtensionService, interface = org.eclipse.smarthome.core.extension.ExtensionService, policy = static, cardinality = 1..1, target = null, bind = setExtensionS
ervice, unbind = unsetExtensionService]
                Reference[name = EventPublisher, interface = org.eclipse.smarthome.core.events.EventPublisher, policy = dynamic, cardinality = 0..1, target = null, bind = setEventPublisher,
unbind = unsetEventPublisher]
        }
        located in bundle = org.eclipse.smarthome.io.rest.core_0.8.0.201512041029 [100]
]
Dynamic information :
  *The component is NOT satisfied
  The following references are not satisfied:
    Reference[name = ExtensionService, interface = org.eclipse.smarthome.core.extension.ExtensionService, policy = static, cardinality = 1..1, target = null, bind = setExtensionService, unbi
nd = unsetExtensionService]
  Component configurations :
    Configuration properties:
      component.name = org.eclipse.smarthome.io.rest.core.binding.ExtensionResource
      component.id = 72
      objectClass = String[org.eclipse.smarthome.io.rest.RESTResource,org.eclipse.smarthome.io.rest.core.extensions.ExtensionResource]
    Instances:
```
The log shows many referencing problems:
```
!SESSION 2015-12-07 22:39:29.852 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_60
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=de_DE
Command-line arguments:  -console

!ENTRY org.eclipse.osgi 4 0 2015-12-07 22:39:30.268
!MESSAGE Bundle reference:file:com.ibm.icu_52.1.1.v201501240615.jar@4 not found.

!ENTRY org.eclipse.osgi 4 0 2015-12-07 22:39:30.293
!MESSAGE Bundle reference:file:org.eclipse.debug.core_3.9.1.v20140805-1629.jar@4 not found.

!ENTRY org.eclipse.osgi 4 0 2015-12-07 22:39:30.310
!MESSAGE Bundle reference:file:org.eclipse.jdt.core_3.10.2.v20150120-1634.jar@4 not found.

!ENTRY org.eclipse.osgi 4 0 2015-12-07 22:39:30.314
!MESSAGE Bundle reference:file:org.eclipse.jdt.launching_3.7.102.v20141111-0953.jar@4 not found.

!ENTRY org.eclipse.equinox.ds 1 0 2015-12-07 22:39:34.082
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.core.persistence.manager. The reference is: Reference[name = ModelRepository, interface = org.eclipse.smarthome.model.core.ModelRepository, policy = dynamic, cardinality = 0..1, target = null, bind = setModelRepository, unbind = unsetModelRepository]

!ENTRY org.eclipse.equinox.ds 1 0 2015-12-07 22:39:34.085
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.core.persistence.manager. The reference is: Reference[name = PersistenceService, interface = org.eclipse.smarthome.core.persistence.PersistenceService, policy = dynamic, cardinality = 0..n, target = null, bind = addPersistenceService, unbind = removePersistenceService]

!ENTRY org.eclipse.equinox.ds 1 0 2015-12-07 22:39:34.088
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.core.persistence.manager. The reference is: Reference[name = ItemRegistry, interface = org.eclipse.smarthome.core.items.ItemRegistry, policy = dynamic, cardinality = 0..1, target = null, bind = setItemRegistry, unbind = unsetItemRegistry]

!ENTRY org.eclipse.equinox.ds 1 0 2015-12-07 22:39:34.096
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.model.persistence.extensions. The reference is: Reference[name = PersistenceService, interface = org.eclipse.smarthome.core.persistence.PersistenceService, policy = dynamic, cardinality = 0..n, target = null, bind = addPersistenceService, unbind = removePersistenceService]

!ENTRY org.eclipse.emf.codegen 4 0 2015-12-07 22:39:35.166
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.emf.codegen [43]
  Unresolved requirement: Require-Bundle: org.eclipse.jdt.core; bundle-version="[3.5.0,4.0.0)"

	at org.eclipse.osgi.container.Module.start(Module.java:434)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1582)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1561)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1533)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1476)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)

!ENTRY org.eclipse.emf.codegen.ecore 4 0 2015-12-07 22:39:35.171
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.emf.codegen.ecore [44]
  Unresolved requirement: Require-Bundle: org.eclipse.jdt.core; bundle-version="[3.5.0,4.0.0)"

	at org.eclipse.osgi.container.Module.start(Module.java:434)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1582)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1561)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1533)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1476)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)

!ENTRY org.eclipse.jdt.debug 4 0 2015-12-07 22:39:35.190
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.jdt.debug [64]
  Unresolved requirement: Require-Bundle: org.eclipse.debug.core; bundle-version="[3.9.0,4.0.0)"

	at org.eclipse.osgi.container.Module.start(Module.java:434)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1582)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1561)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1533)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1476)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)

!ENTRY org.eclipse.equinox.ds 1 0 2015-12-07 22:39:35.766
!MESSAGE Could not bind a reference of component ConfigDescriptionRegistry. The reference is: Reference[name = ConfigOptionProvider, interface = org.eclipse.smarthome.config.core.ConfigOptionProvider, policy = dynamic, cardinality = 0..n, target = null, bind = addConfigOptionProvider, unbind = removeConfigOptionProvider]

!ENTRY org.eclipse.equinox.ds 1 0 2015-12-07 22:39:35.771
!MESSAGE Could not bind a reference of component ConfigDescriptionRegistry. The reference is: Reference[name = ConfigDescriptionProvider, interface = org.eclipse.smarthome.config.core.ConfigDescriptionProvider, policy = dynamic, cardinality = 0..n, target = null, bind = addConfigDescriptionProvider, unbind = removeConfigDescriptionProvider]

!ENTRY org.eclipse.equinox.ds 1 0 2015-12-07 22:39:35.793
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.config.discovery.internal.DiscoveryServiceRegistry. The reference is: Reference[name = DiscoveryService, interface = org.eclipse.smarthome.config.discovery.DiscoveryService, policy = dynamic, cardinality = 0..n, target = null, bind = addDiscoveryService, unbind = removeDiscoveryService]

!ENTRY org.eclipse.equinox.ds 1 0 2015-12-07 22:39:36.173
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.core.binding.BindingInfoRegistry. The reference is: Reference[name = BindingInfoProvider, interface = org.eclipse.smarthome.core.binding.BindingInfoProvider, policy = dynamic, cardinality = 0..n, target = null, bind = addBindingInfoProvider, unbind = removeBindingInfoProvider]

!ENTRY org.eclipse.equinox.ds 1 0 2015-12-07 22:39:36.199
!MESSAGE Could not bind a reference of component ConfigStatusService. The reference is: Reference[name = ConfigStatusProvider, interface = org.eclipse.smarthome.config.core.status.ConfigStatusProvider, policy = dynamic, cardinality = 0..n, target = null, bind = addConfigStatusProvider, unbind = removeConfigStatusProvider]

!ENTRY org.eclipse.equinox.ds 1 0 2015-12-07 22:39:36.276
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.core.itemregistry. The reference is: Reference[name = ItemProvider, interface = org.eclipse.smarthome.core.items.ItemProvider, policy = dynamic, cardinality = 0..n, target = null, bind = addProvider, unbind = removeProvider]

!ENTRY org.eclipse.equinox.ds 1 0 2015-12-07 22:39:36.283
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.core.itemregistry. The reference is: Reference[name = StateDescriptionProvider, interface = org.eclipse.smarthome.core.types.StateDescriptionProvider, policy = dynamic, cardinality = 0..n, target = null, bind = addStateDescriptionProvider, unbind = removeStateDescriptionProvider]

!ENTRY org.eclipse.equinox.ds 1 0 2015-12-07 22:39:36.380
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.core.thing.ThingRegistry. The reference is: Reference[name = ThingProvider, interface = org.eclipse.smarthome.core.thing.ThingProvider, policy = dynamic, cardinality = 0..n, target = null, bind = addProvider, unbind = removeProvider]

!ENTRY org.eclipse.equinox.ds 1 0 2015-12-07 22:39:36.387
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.core.thing.link.ItemChannelLinkRegistry. The reference is: Reference[name = ItemChannelLinkProvider, interface = org.eclipse.smarthome.core.thing.link.ItemChannelLinkProvider, policy = dynamic, cardinality = 0..n, target = null, bind = addProvider, unbind = removeProvider]

!ENTRY org.eclipse.equinox.ds 1 0 2015-12-07 22:39:36.393
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.core.thing.type.ThingTypeRegistry. The reference is: Reference[name = ThingTypeProvider, interface = org.eclipse.smarthome.core.thing.binding.ThingTypeProvider, policy = dynamic, cardinality = 0..n, target = null, bind = addThingTypeProvider, unbind = removeThingTypeProvider]

!ENTRY org.eclipse.equinox.ds 1 0 2015-12-07 22:39:36.407
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.core.thing.link.ItemThingLinkRegistry. The reference is: Reference[name = ItemThingLinkProvider, interface = org.eclipse.smarthome.core.thing.link.ItemThingLinkProvider, policy = dynamic, cardinality = 0..n, target = null, bind = addProvider, unbind = removeProvider]

!ENTRY org.eclipse.equinox.ds 1 0 2015-12-07 22:39:36.429
!MESSAGE Could not bind a reference of component org.openhab.persistence.rrd4j. The reference is: Reference[name = ItemRegistry, interface = org.openhab.core.items.ItemRegistry, policy = dynamic, policy-option = reluctant, cardinality = 0..1, target = null, bind = setItemRegistry, unbind = unsetItemRegistry, updated = null]

!ENTRY org.openhab.persistence.rrd4j 2 0 2015-12-07 22:39:36.676
!MESSAGE [SCR] Found components with duplicated names! Details: 
Component1 : Component[
	name = org.openhab.persistence.rrd4j
	activate = activate
	deactivate = deactivate
	modified = 
	configuration-policy = optional
	configuration-pid = org.openhab.rrd4j
	factory = null
	autoenable = true
	immediate = true
	implementation = org.openhab.persistence.rrd4j.internal.RRD4jService
	state = Unsatisfied
	properties = 
	serviceFactory = false
	serviceInterface = [org.openhab.core.persistence.PersistenceService]
	references = {
		Reference[name = ItemRegistry, interface = org.openhab.core.items.ItemRegistry, policy = dynamic, policy-option = reluctant, cardinality = 0..1, target = null, bind = setItemRegistry, unbind = unsetItemRegistry, updated = null]
	}
	located in bundle = org.openhab.persistence.rrd4j_1.8.0.201512060201 [167]
]
Component2: Component[
	name = org.openhab.persistence.rrd4j
	activate = activate
	deactivate = deactivate
	modified = 
	configuration-policy = optional
	configuration-pid = org.openhab.rrd4j
	factory = null
	autoenable = true
	immediate = true
	implementation = org.openhab.persistence.rrd4j.internal.RRD4jService
	state = Unsatisfied
	properties = 
	serviceFactory = false
	serviceInterface = [org.openhab.core.persistence.PersistenceService]
	references = {
		Reference[name = ItemRegistry, interface = org.openhab.core.items.ItemRegistry, policy = dynamic, policy-option = reluctant, cardinality = 0..1, target = null, bind = setItemRegistry, unbind = unsetItemRegistry, updated = null]
	}
	located in bundle = org.openhab.persistence.rrd4j_1.8.0.201512041034 [172]
]  

!ENTRY org.openhab.persistence.rrd4j 2 0 2015-12-07 22:39:36.680
!MESSAGE [SCR] Found components with duplicated names! Details: 
Component1 : Component[
	name = org.openhab.persistence.rrd4j.chartservlet
	activate = activate
	deactivate = deactivate
	modified = 
	configuration-policy = optional
	factory = null
	autoenable = true
	immediate = false
	implementation = org.openhab.persistence.rrd4j.internal.charts.RRD4jChartServlet
	state = Unsatisfied
	properties = 
	serviceFactory = false
	serviceInterface = [org.openhab.ui.chart.ChartProvider]
	references = {
		Reference[name = HttpService, interface = org.osgi.service.http.HttpService, policy = dynamic, cardinality = 1..1, target = null, bind = setHttpService, unbind = unsetHttpService]
		Reference[name = ItemUIRegistry, interface = org.openhab.ui.items.ItemUIRegistry, policy = dynamic, cardinality = 1..1, target = null, bind = setItemUIRegistry, unbind = unsetItemUIRegistry]
	}
	located in bundle = org.openhab.persistence.rrd4j_1.8.0.201512060201 [167]
]
Component2: Component[
	name = org.openhab.persistence.rrd4j.chartservlet
	activate = activate
	deactivate = deactivate
	modified = 
	configuration-policy = optional
	factory = null
	autoenable = true
	immediate = false
	implementation = org.openhab.persistence.rrd4j.internal.charts.RRD4jChartServlet
	state = Unsatisfied
	properties = 
	serviceFactory = false
	serviceInterface = [org.openhab.ui.chart.ChartProvider]
	references = {
		Reference[name = HttpService, interface = org.osgi.service.http.HttpService, policy = dynamic, cardinality = 1..1, target = null, bind = setHttpService, unbind = unsetHttpService]
		Reference[name = ItemUIRegistry, interface = org.openhab.ui.items.ItemUIRegistry, policy = dynamic, cardinality = 1..1, target = null, bind = setItemUIRegistry, unbind = unsetItemUIRegistry]
	}
	located in bundle = org.openhab.persistence.rrd4j_1.8.0.201512041034 [172]
]  

!ENTRY org.eclipse.equinox.ds 1 0 2015-12-07 22:39:36.693
!MESSAGE Could not bind a reference of component org.openhab.persistence.rrd4j. The reference is: Reference[name = ItemRegistry, interface = org.openhab.core.items.ItemRegistry, policy = dynamic, policy-option = reluctant, cardinality = 0..1, target = null, bind = setItemRegistry, unbind = unsetItemRegistry, updated = null]

!ENTRY org.eclipse.equinox.ds 1 0 2015-12-07 22:39:37.638
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.ui. The reference is: Reference[name = ItemUIProvider, interface = org.eclipse.smarthome.ui.items.ItemUIProvider, policy = dynamic, cardinality = 0..n, target = null, bind = addItemUIProvider, unbind = removeItemUIProvider]

!ENTRY org.eclipse.equinox.ds 1 0 2015-12-07 22:39:37.642
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.io.rest.sitemap. The reference is: Reference[name = SitemapProvider, interface = org.eclipse.smarthome.model.sitemap.SitemapProvider, policy = dynamic, cardinality = 0..n, target = null, bind = addSitemapProvider, unbind = removeSitemapProvider]

!ENTRY org.eclipse.equinox.ds 1 0 2015-12-07 22:39:37.657
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.ui.chart. The reference is: Reference[name = ChartProvider, interface = org.eclipse.smarthome.ui.chart.ChartProvider, policy = dynamic, cardinality = 0..n, target = null, bind = addChartProvider, unbind = removeChartProvider]

!ENTRY org.eclipse.equinox.ds 1 0 2015-12-07 22:39:37.677
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.ui.chart.defaultprovider. The reference is: Reference[name = PersistenceService, interface = org.eclipse.smarthome.core.persistence.PersistenceService, policy = dynamic, cardinality = 0..n, target = null, bind = addPersistenceService, unbind = removePersistenceService]

!ENTRY org.eclipse.equinox.ds 1 0 2015-12-07 22:39:37.980
!MESSAGE Could not bind a reference of component org.openhab.core.compat1x.bindingconfigreaderfactory. The reference is: Reference[name = BindingConfigReader, interface = org.openhab.model.item.binding.BindingConfigReader, policy = dynamic, cardinality = 0..n, target = null, bind = addBindingConfigReader, unbind = removeBindingConfigReader]

!ENTRY org.eclipse.equinox.ds 1 0 2015-12-07 22:39:37.985
!MESSAGE Could not bind a reference of component org.openhab.core.compat1x.actionservicefactory. The reference is: Reference[name = ActionService, interface = org.openhab.core.scriptengine.action.ActionService, policy = dynamic, cardinality = 0..n, target = null, bind = addActionService, unbind = removeActionService]

!ENTRY org.eclipse.equinox.ds 1 0 2015-12-07 22:39:37.991
!MESSAGE Could not bind a reference of component org.openhab.core.compat1x.ttsservicefactory. The reference is: Reference[name = TTSService, interface = org.openhab.io.multimedia.tts.TTSService, policy = dynamic, cardinality = 0..n, target = null, bind = addTTSService, unbind = removeTTSService]

!ENTRY org.eclipse.equinox.ds 1 0 2015-12-07 22:39:37.997
!MESSAGE Could not bind a reference of component org.openhab.core.compat1x.autoupdateproviderdelegate. The reference is: Reference[name = AutoUpdateBindingProvider, interface = org.openhab.core.autoupdate.AutoUpdateBindingProvider, policy = dynamic, cardinality = 0..n, target = null, bind = addAutoUpdateBindingProvider, unbind = removeAutoUpdateBindingProvider]
```

**Comment by kaikreuzer** [comment] 2015-12-08 07:50
I have just tested build 435 and it works all fine - I cannot reproduce your problem.
The log file you posted does not not look at all like an openhab.log file. Are you sure that you are launching it through start.sh?

**Comment by SuperOok** [comment] 2015-12-08 15:40
I'm running it on Windows 8.1 for test purposes, so launching start.bat. I'll check later the location of the logfile. Was the only ones I found; some <longerID>.log but not openhab.log

**Comment by SuperOok** [comment] 2015-12-08 22:55
The log above is from runtime\server\configuration\1449525689744.log

I reran the application but still no Icons in the basic UI. Calling any icon URL manually gives a 404 from the Jetty, e.g. http://localhost:8080/icon/switch?state=OFF&format=svg

```
HTTP ERROR 404

Problem accessing /icon/switch. Reason:

    Not Found
```

Find the openhab.log below.

```
2015-12-08 23:46:44.756 [WARN ] [.p.rrd4j.internal.RRD4jService] - Unknown property name : org.openhab.persistence.rrd4j
2015-12-08 23:46:44.756 [INFO ] [.p.rrd4j.internal.RRD4jService] - Removing invalid defintion component = null heartbeat = 0 min/max = 0.0/0.0 step = 0 0 archives(s) = [] 0 items(s) = []
2015-12-08 23:46:44.914 [WARN ] [.p.rrd4j.internal.RRD4jService] - Unknown property name : org.openhab.persistence.rrd4j
2015-12-08 23:46:44.914 [INFO ] [.p.rrd4j.internal.RRD4jService] - Removing invalid defintion component = null heartbeat = 0 min/max = 0.0/0.0 step = 0 0 archives(s) = [] 0 items(s) = []
2015-12-08 23:46:44.964 [INFO ] [s.ui.paper.internal.PaperUIApp] - Started Paper UI at /ui
2015-12-08 23:46:45.166 [ERROR] [p.r.i.charts.RRD4jChartServlet] - Error during servlet startup
org.osgi.service.http.NamespaceException: The alias '/rrdchart.png' is already in use.
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.registerServlet(ProxyServlet.java:169) ~[na:na]
	at org.eclipse.equinox.http.servlet.internal.HttpServiceImpl.registerServlet(HttpServiceImpl.java:66) ~[na:na]
	at org.openhab.persistence.rrd4j.internal.charts.RRD4jChartServlet.activate(RRD4jChartServlet.java:121) ~[na:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_60]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_60]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_60]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_60]
	at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:235) [org.eclipse.equinox.ds_1.4.200.v20131126-2331.jar:na]
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146) [org.eclipse.equinox.ds_1.4.200.v20131126-2331.jar:na]
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345) [org.eclipse.equinox.ds_1.4.200.v20131126-2331.jar:na]
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620) [org.eclipse.equinox.ds_1.4.200.v20131126-2331.jar:na]
	at org.eclipse.equinox.internal.ds.ServiceReg.getService(ServiceReg.java:53) [org.eclipse.equinox.ds_1.4.200.v20131126-2331.jar:na]
	at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse$1.run(ServiceFactoryUse.java:212) [org.eclipse.osgi_3.10.2.v20150203-1939.jar:na]
	at java.security.AccessController.doPrivileged(Native Method) [na:1.8.0_60]
	at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.factoryGetService(ServiceFactoryUse.java:210) [org.eclipse.osgi_3.10.2.v20150203-1939.jar:na]
	at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.getService(ServiceFactoryUse.java:111) [org.eclipse.osgi_3.10.2.v20150203-1939.jar:na]
	at org.eclipse.osgi.internal.serviceregistry.ServiceConsumer$2.getService(ServiceConsumer.java:45) [org.eclipse.osgi_3.10.2.v20150203-1939.jar:na]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.getService(ServiceRegistrationImpl.java:496) [org.eclipse.osgi_3.10.2.v20150203-1939.jar:na]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.getService(ServiceRegistry.java:461) [org.eclipse.osgi_3.10.2.v20150203-1939.jar:na]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.getService(BundleContextImpl.java:619) [org.eclipse.osgi_3.10.2.v20150203-1939.jar:na]
	at org.eclipse.equinox.internal.ds.InstanceProcess.getService(InstanceProcess.java:730) [org.eclipse.equinox.ds_1.4.200.v20131126-2331.jar:na]
	at org.eclipse.equinox.internal.ds.model.ComponentReference.bind(ComponentReference.java:347) [org.eclipse.equinox.ds_1.4.200.v20131126-2331.jar:na]
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.bindReference(ServiceComponentProp.java:444) [org.eclipse.equinox.ds_1.4.200.v20131126-2331.jar:na]
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.bind(ServiceComponentProp.java:218) [org.eclipse.equinox.ds_1.4.200.v20131126-2331.jar:na]
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:343) [org.eclipse.equinox.ds_1.4.200.v20131126-2331.jar:na]
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620) [org.eclipse.equinox.ds_1.4.200.v20131126-2331.jar:na]
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197) [org.eclipse.equinox.ds_1.4.200.v20131126-2331.jar:na]
	at org.eclipse.equinox.internal.ds.Resolver.buildNewlySatisfied(Resolver.java:473) [org.eclipse.equinox.ds_1.4.200.v20131126-2331.jar:na]
	at org.eclipse.equinox.internal.ds.Resolver.enableComponents(Resolver.java:217) [org.eclipse.equinox.ds_1.4.200.v20131126-2331.jar:na]
	at org.eclipse.equinox.internal.ds.SCRManager.performWork(SCRManager.java:816) [org.eclipse.equinox.ds_1.4.200.v20131126-2331.jar:na]
	at org.eclipse.equinox.internal.ds.SCRManager$QueuedJob.dispatch(SCRManager.java:783) [org.eclipse.equinox.ds_1.4.200.v20131126-2331.jar:na]
	at org.eclipse.equinox.internal.ds.WorkThread.run(WorkThread.java:89) [org.eclipse.equinox.ds_1.4.200.v20131126-2331.jar:na]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_60]
2015-12-08 23:46:45.253 [INFO ] [.u.d.internal.DashboardService] - Started dashboard at /start
2015-12-08 23:46:45.523 [INFO ] [.s.u.b.i.servlet.WebAppServlet] - Started Basic UI at /basicui/app
2015-12-08 23:46:45.526 [INFO ] [.s.u.c.i.servlet.WebAppServlet] - Started Classic UI at /classicui/app
2015-12-08 23:46:45.559 [INFO ] [.o.core.internal.CoreActivator] - openHAB runtime has been started (v2.0.0, build 201512070207).
2015-12-08 23:46:45.601 [INFO ] [.e.s.m.c.i.ModelRepositoryImpl] - Loading model 'demo.sitemap'
2015-12-08 23:46:45.766 [INFO ] [s.c.d.internal.PersistentInbox] - Added new thing 'yahooweather:weather:20065906' to inbox.
2015-12-08 23:46:45.789 [INFO ] [.e.s.m.c.i.ModelRepositoryImpl] - Loading model 'demo.things'
2015-12-08 23:46:45.990 [INFO ] [.e.s.m.c.i.ModelRepositoryImpl] - Loading model 'logging.persist'
2015-12-08 23:46:46.005 [INFO ] [.e.s.m.c.i.ModelRepositoryImpl] - Loading model 'rrd4j.persist'
2015-12-08 23:46:46.045 [INFO ] [.e.s.m.c.i.ModelRepositoryImpl] - Loading model 'demo.rules'
2015-12-08 23:46:46.501 [INFO ] [.e.s.m.c.i.ModelRepositoryImpl] - Loading model 'demo.script'
2015-12-08 23:46:46.570 [INFO ] [.e.s.m.c.i.ModelRepositoryImpl] - Loading model 'demo.items'
2015-12-08 23:46:48.752 [INFO ] [.b.a.handler.AstroThingHandler] - Scheduled astro DailyJob at midnight for thing astro:sun:home
2015-12-08 23:46:48.754 [INFO ] [.b.a.handler.AstroThingHandler] - Scheduled astro PositionalJob with interval of 60 seconds for thing astro:sun:home
2015-12-08 23:47:23.965 [INFO ] [s.ui.paper.internal.PaperUIApp] - Stopped Paper UI
2015-12-08 23:47:23.967 [INFO ] [.u.d.internal.DashboardService] - Stopped dashboard
2015-12-08 23:47:23.972 [INFO ] [.s.u.b.i.servlet.WebAppServlet] - Stopped Basic UI
2015-12-08 23:47:23.981 [INFO ] [.s.u.c.i.servlet.WebAppServlet] - Stopped Classic UI
```

**Comment by SuperOok** [comment] 2015-12-09 20:11
I tried the demo items and removed all <icon> tags; still the same: I got 404 broken icons for all elements. So I guess it's a different issue.

**Comment by xsnrg** [comment] 2015-12-09 20:38
Agreed, unfortunately.  I will copy my findings to a new ticket as a different issue.

**Comment by kaikreuzer** [comment] 2015-12-10 08:24
@SuperOok Ok, I just tried the latest openHAB build on Windows 10 and I can reproduce the issue. The icon servlet simply is not registered for some reason and thus all requests result in an 404. I will analyse that closer and come back to you.

**Comment by kaikreuzer** [comment] 2015-12-10 16:31
That was a tricky one - it indeed occurred only on WIndows. Should now be fixed with the next build!

**Closed** 2015-12-10 16:30 UTC

**Comment by SuperOok** [comment] 2015-12-11 16:02
Great!
