### ISSUE TITLE
persistence restoreOnStartup not working.

### ISSUE THREAD

**Issue by brutevinch** [openhab/openhab2#279] opened 2015-06-07 10:58 UTC
Persistence is configured correct. When i use mysql data writes to mysql fine but not restored after openhab2 restarts. i tried to use rrd4j - same thing, date creates in userdata  but after restart not restored. Item is Switch. may be restoreOnStartup not working in openhab core?

**Comment by kgoderis** [comment] 2015-06-07 11:01
See https://github.com/openhab/openhab2/issues/270

K

**Comment by brutevinch** [comment] 2015-06-07 11:06
@kgoderis AHhah. I do not understand anything there) i'm not programmer. is it bug or my mistake?

**Comment by kgoderis** [comment] 2015-06-07 11:10
A bug

**Comment by kaikreuzer** [comment] 2015-06-07 12:25
duplicate of #270

**Closed by kaikreuzer** 2015-06-07 12:25 UTC
Labels: duplicate
