### ISSUE TITLE
[lifx] some lights stop responding after few hours

### ISSUE THREAD

**Issue by petrklus** [openhab/openhab2#328] opened 2015-08-08 10:04 UTC
In an attempt to use the LiFX binding, I've created minimal installation of OH2 with only the LiFX binding in it.

Initially it worked great and detected all of my bulbs. However, after ~8 hours of running, I can no longer control one of my bulbs:

```
2015-08-08 12:00:18 [INFO ] [runtime.busevents             :22   ] - lifx_light_D073D500072C_color received command 55
2015-08-08 12:00:19 [DEBUG] [io.rest.core.item.ItemResource:201  ] - Received HTTP POST request at 'items/lifx_light_D073D500072C_color' with value '36'.
2015-08-08 12:00:19 [DEBUG] [.c.thing.internal.ThingManager:222  ] - Delegating command '36' for item 'lifx_light_D073D500072C_color' to handler for channel 'lifx:light:D073D500072C:color'
2015-08-08 12:00:19 [ERROR] [s.b.l.handler.LifxLightHandler:91   ] - Error while updating light.java.lang.NullPointerException: null
```

I've tried few others and those work well. I can control the bulb in question without any trouble using the official app on my phone.

**Comment by petrklus** [comment] 2015-08-08 10:08
Debug log:
[oh2_lifx.log | uploaded via ZenHub](https://files.zenhub.io/55c5d4a6b812414371e14eb9)

**Comment by kaikreuzer** [comment] 2015-08-08 20:28
The LIFX binding has some known resource leaks, see https://bugs.eclipse.org/bugs/show_bug.cgi?id=464961. Unfortunately, LIFX does not provide any further support on the Android (Java) client library, see https://github.com/LIFX/lifx-sdk-android/blob/master/README.md, so this will not be fixed in there.

I guess the only way is to find some other Java LIFX library that is actively maintained. I am not aware of any though :-|

**Closed by kaikreuzer** 2015-08-08 20:28 UTC

**Comment by kgoderis** [comment] 2015-08-09 09:50
hum.. ;-) So, like jupnp we can maybe branch and integrate into ESH?

**Comment by kaikreuzer** [comment] 2015-08-11 09:48
> So, like jupnp we can maybe branch and integrate into ESH?

Well, @dnobel already has a branch of the used library: https://github.com/dnobel/lifx-sdk-java
The problem is that this would need to be maintained by somebody. And this would essentially mean to read the protocol docs of LIFX in detail (https://github.com/lifx/lifx-protocol-docs) and implement all this stuff. If you come up with a volunteer, let me know :-)

**Comment by dnobel** [comment] 2015-08-11 10:01
What about https://github.com/besherman/lifx-sdk-java? The version 2.0 should work. But it seems like there also was no commit since feb this year.

**Comment by kgoderis** [comment] 2015-08-11 10:04
Interesting. I did not look at the code, but maybe it is also an opportunity to resolve the threading issues?

**Comment by dnobel** [comment] 2015-08-11 10:10
We could give it at least a try. If the developer does not want to continue the development it might be a starting point for a new library. Definitely better than the outdated original LIFX library But however, as Kai said we need someone who has to take care about it.

**Comment by petrklus** [comment] 2015-08-11 10:18
Not sure it was mentioned here before - there is now official documentation
for the LAN protocol:

http://lan.developer.lifx.com/

and useful

https://community.lifx.com/t/building-a-lifx-packet/59

Best,

Petr

**Comment by kgoderis** [comment] 2015-08-12 07:07
Just a thought: would we simple import the library and maintain it, or rather, integrate it completely in the LIFX binding? after all, in contradiction to the jupnp lib, there is only one binding using this lib. By integrating it completely, we can make use of the ThreadPools, do away with some APIs, better use the event/listener pattern and so forth

**Comment by kaikreuzer** [comment] 2015-08-15 19:54
Maintaining the LIFX library outside of the binding would have the benefit to others, that this library could be used in other projects as well. So there is a better chance to find contributors for it.
