### ISSUE TITLE
current target platform does not include required bundles to run Groovy unit tests

### ISSUE THREAD

**Issue by marcelrv** [openhab/openhab2#112] opened 2015-01-15 14:18 UTC
when compile test scenario's migrated from OH11 it complains about missing junit 

[INFO] Adding repository http://dist.springsource.org/release/GRECLIPSE/e4.4    [ERROR] Internal error: java.lang.RuntimeException: Failed to resolve target definition C:\Temp\OH2\openhab2\targetplatform\openhab.target: Could not find "org.junit/4.11.0.v201303080030" in the repositories of the current location -> [Help 1]                                                                             

also groovy is not in the target, would be great to add that as well

**Comment by kaikreuzer** [comment] 2015-01-16 22:23
OH11? You are far ahead ;-)
No, seriously: I cannot see a GRECLIPSE/e4.4 or a junit 4.11.0 reference in the openhab.target file (https://github.com/openhab/openhab2/blob/master/targetplatform/openhab.target). So where does this error come from?

> also groovy is not in the target, would be great to add that as well
You are right, this is only in the smarthome.target of ESH. The cause is probably that there were no Groovy unit tests so far in OH2 - feel free to add it to the TP with a PR, which brings the first Groovy tests!

**Comment by marcelrv** [comment] 2015-01-19 11:42
Argh... yes years ahead :)

The  GRECLIPSE/e4.4 part indeed came from my hacking on the target file.
The issue that I'm struggling is that I don't seem to be able to make a working setup of target file/Eclipse setup that does not result in errors. 

Using test here https://github.com/marcelrv/openhab2/tree/maxcube-testpack-wip

No matter what I do either in eclipse or in maven something ends up as missing dependency.
in Eclipse it does not show with any errors in the code, but execution in the IDE gives  `Required plug-in 'org.eclipse.jdt.junit.runtime' could not be found.`


in maven it fails with
```
[INFO]                                                                          
[INFO] --- tycho-p2-plugin:0.21.0:update-local-index (default-update-local-index) @ org.openhab.binding.max ---                                                 
[INFO]                                                                          
[INFO] ------------------------------------------------------------------------ 
[INFO] Building openHAB MAX! Binding Tests 2.0.0-SNAPSHOT                       
[INFO] ------------------------------------------------------------------------ 
[INFO]                                                                          
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ org.openhab.binding.max.test ---                                                                      
[INFO] Deleting C:\Temp\OH2\openhab2\addons\binding\org.openhab.binding.max.test\target                                                                         
[INFO]                                                                          
[INFO] --- tycho-packaging-plugin:0.21.0:build-qualifier (default-build-qualifier) @ org.openhab.binding.max.test ---                                           
[INFO] The project's OSGi version is 2.0.0.201501191121                         
[INFO]                                                                          
[INFO] --- tycho-packaging-plugin:0.21.0:validate-id (default-validate-id) @ org.openhab.binding.max.test ---                                                   
[INFO]                                                                          
[INFO] --- tycho-packaging-plugin:0.21.0:validate-version (default-validate-version) @ org.openhab.binding.max.test ---                                         
[INFO]                                                                          
[INFO] --- maven-resources-plugin:2.4.3:resources (default-resources) @ org.openhab.binding.max.test ---                                                        
[INFO] Using 'UTF-8' encoding to copy filtered resources.                       
[INFO] skip non existing resourceDirectory C:\Temp\OH2\openhab2\addons\binding\org.openhab.binding.max.test\src\main\resources                                  
[INFO]                                                                          
[INFO] --- tycho-compiler-plugin:0.21.0:compile (default-compile) @ org.openhab.binding.max.test ---                                                            
[INFO] Compiling 4 source files to C:\Temp\OH2\openhab2\addons\binding\org.openhab.binding.max.test\target\classes                                              
[INFO]                                                                          
[INFO] --- maven-resources-plugin:2.4.3:testResources (default-testResources) @ org.openhab.binding.max.test ---                                                
[INFO] Using 'UTF-8' encoding to copy filtered resources.                       
[INFO] skip non existing resourceDirectory C:\Temp\OH2\openhab2\addons\binding\org.openhab.binding.max.test\src\test\resources                                  
[INFO]                                                                          
[INFO] --- target-platform-configuration:0.21.0:target-platform (default-target-platform) @ org.openhab.binding.max.test ---                                    
[INFO]                                                                          
[INFO] --- tycho-packaging-plugin:0.21.0:package-plugin (default-package-plugin) @ org.openhab.binding.max.test ---                                             
[INFO] Building jar: C:\Temp\OH2\openhab2\addons\binding\org.openhab.binding.max.test\target\org.openhab.binding.max.test-2.0.0-SNAPSHOT.jar                    
[INFO]                                                                          
[INFO] --- tycho-p2-plugin:0.21.0:p2-metadata-default (default-p2-metadata-default) @ org.openhab.binding.max.test ---                                          
[INFO]                                                                          
[INFO] --- tycho-surefire-plugin:0.21.0:test (default-test) @ org.openhab.binding.max.test ---                                                                  
[INFO] Cannot complete the request.  Generating details.                        
[INFO] Cannot complete the request.  Generating details.                        
[INFO] {osgi.ws=gtk, osgi.os=linux, osgi.arch=x86, org.eclipse.update.install.features=true}                                                                    [ERROR] Cannot resolve project dependencies:                                    [ERROR]   You requested to install 'bundle org.eclipse.core.runtime 0.0.0' but it could not be found                                                            [ERROR]                                                                         
[INFO] ------------------------------------------------------------------------ 
[INFO] Reactor Summary:                                                         
[INFO]                                                                          
[INFO] openHAB ............................................ SUCCESS [  0.234 s] 
[INFO] openHAB Add-ons .................................... SUCCESS [  0.015 s] 
[INFO] openHAB Bindings ................................... SUCCESS [  0.016 s] 
[INFO] Sonos Binding ...................................... SUCCESS [  2.995 s] 
[INFO] openHAB MAX! Binding ............................... SUCCESS [  1.981 s] 
[INFO] openHAB MAX! Binding Tests ......................... FAILURE [  1.467 s] 
[INFO] NetworkHealth Binding .............................. SKIPPED             
[INFO] openHAB Bundles .................................... SKIPPED             
[INFO] openHAB Core Components ............................ SKIPPED             
[INFO] openHAB Core ....................................... SKIPPED             
[INFO] openHAB Initializer ................................ SKIPPED             
[INFO] openHAB Core 1.x Compatibility Layer ............... SKIPPED             
[INFO] openHAB I/O Components ............................. SKIPPED             
[INFO] openHAB Serial Transport ........................... SKIPPED             
[INFO] openHAB Jetty ...................................... SKIPPED             
[INFO] openHAB REST API Documentation ..................... SKIPPED             
[INFO] openHAB UI Components .............................. SKIPPED             
[INFO] openHAB Dashboard UI ............................... SKIPPED             
[INFO] openHAB Features ................................... SKIPPED             
[INFO] openHAB Dependencies ............................... SKIPPED             
[INFO] openHAB Minimal Dependencies ....................... SKIPPED             
[INFO] openHAB Runtime .................................... SKIPPED             
[INFO] openHAB Minimal Runtime ............................ SKIPPED             
[INFO] openHAB Products ................................... SKIPPED             
[INFO] openHAB Runtime Application ........................ SKIPPED             
[INFO] openHAB Minimal Runtime ............................ SKIPPED             
[INFO] openHAB Target Platform ............................ SKIPPED             
[INFO] openHAB Distribution ............................... SKIPPED             
[INFO] ------------------------------------------------------------------------ 
[INFO] BUILD FAILURE                                                            
[INFO] ------------------------------------------------------------------------ 
[INFO] Total time: 26.036 s                                                     
[INFO] Finished at: 2015-01-19T12:21:43+01:00                                   
[INFO] Final Memory: 78M/525M                                                   
[INFO] ------------------------------------------------------------------------ 

[ERROR] Failed to execute goal org.eclipse.tycho:tycho-surefire-plugin:0.21.0:test (default-test) on
 project org.openhab.binding.max.test: Execution default-test of goal org.eclipse.tycho:tycho-surefire-plugin:0.21.0:test 
failed: No solution found because the problem is unsatisfiable.: [Unable to satisfy dependency from tycho-extra-1421666503906 0.0.0.1421666503906 to bundle org.eclipse.core.runtime 0.0.0.; 
Unable to satisfy dependency from tycho-1421666503906 0.0.0.1421666503906 to bundle org.eclipse.core.runtime 0.0.0.; No solution found because the problem is unsatisfiable.] -> [Help 1]                                            
[ERROR]                                                                         
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.                                                                             
[ERROR] Re-run Maven using the -X switch to enable full debug logging.          


```

**Comment by marcelrv** [comment] 2015-01-19 21:49
Okay, I managed to get it running by merging the target from ESH and OH2.
I'll make a PR for it shortly incl the MAX! tests

**Comment by marcelrv** [comment] 2015-01-21 22:30
Hi Kai,

Some progress here, but still not getting it...
So I can run the regular Junit tests, and can run the groovy test. However, the groovy stuff is failing on the very first part (copied from hue test in smarthome):

```
	    ManagedThingProvider managedThingProvider
    VolatileStorageService volatileStorageService = new VolatileStorageService()


    @Before
    void setUp() {
        registerService(volatileStorageService)
        managedThingProvider = getService(ThingProvider, ManagedThingProvider)
        assertThat managedThingProvider, is(notNullValue())
    }
```

I have included in the run most of the smarthome jars, the thing starts (e.g. I can see the it discovers a cube) but it managedThingProvider remains null. Hence the remaining tests fail as well.

Any suggestions on what to include to get the managed thing provider running?

**Comment by kaikreuzer** [comment] 2015-01-22 07:33
@dnobel, do you have maybe any quick idea what might be missing?

**Comment by marcelrv** [comment] 2015-01-22 07:52
Hi @dnobel

The latest development wrt this is here https://github.com/marcelrv/openhab2/tree/maxcube-testpack-wip.   I'm trying to run the org.openhab.binding.max.test
The openhab target is adjusted to include all the stuff that is in the esh target.

In the IDE the regular java tests are running as well as the groovy test, but the groovy tests all fail. When building with maven only the Junit tests seem to run and the groovy stuff ignored.

Hope you have a suggestion indeed.

**Comment by dnobel** [comment] 2015-01-22 17:21
Hi,

first of all I´m very happy to hear that you want to implement a test for a binding :).

I think the problem is, that DS bundle is not started. So please check in your Run Configuration, that the "equinox.ds" plugin is part of the runtime and that "autostart" is set to true. You also need to start bundles, which contains components you need. The hue binding should be a good reference for it. I know it´s a little bit tricky ;). 

There is also documentation available at hhttps://github.com/eclipse/smarthome/blob/master/docs/sources/development/unittesting.md, which describes how to configure the launch config in Eclipse and also for maven. I´m not sure if you have found it already. 

I hope that helps for the moment.

Regards

Dennis

**Comment by marcelrv** [comment] 2015-01-23 00:51
Thanks Dennis,

That was enough hint to get in done. Still lot of trial & Error, the missing ones that did the trick were not identified as required by eclipse. (the various smarrthome.*.xml ones)
PR created #116

**Comment by kaikreuzer** [comment] 2015-02-11 15:24
PR #116 has been merged now.
Regarding Groovy in the IDE, this will be solved once we have an IDE setup based on Eclipse Oompf.

**Closed by kaikreuzer** 2015-02-11 15:24 UTC

**Comment by svilenvul** [comment] 2016-03-28 09:10
Hi,

is this issue fixed at the moment ?

[MaxBridgeHandlerOSGiTest.groovy](https://github.com/openhab/openhab2-addons/blob/master/addons/binding/org.openhab.binding.max.test/src/test/groovy/org/openhab/binding/max/test/MaxBridgeHandlerOSGiTest.groovy) is not executed in the [last Jenkins build](https://openhab.ci.cloudbees.com/job/PR-openHAB2-Addons/lastBuild/testReport/).

After a research, I found that Groovy Eclipse compiler is missing in the Tycho compiler plugin configuration.

I tested it and I will open a pull request that fixes the issue in MAX! Binding Tests.

**Comment by marcelrv** [comment] 2016-03-28 11:58
@kaikreuzer 

> Regarding Groovy in the IDE, this will be solved once we have an IDE setup based on Eclipse Oompf.

Is this still in the plan. I don't think current Oompf OH2 eclipse environment is very supportive of the groovy stuff (or... I just don't know well enough how Groovy is suppose to work)

@svilenvul 
Thanks for finding this. I aslway assumed it is working fine as it reports:
```
Running org.openhab.binding.max.test.MaxBridgeHandlerOSGiTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 7.982 sec - in org.openhab.binding.max.test.MaxBridgeHandlerOSGiTest
maxCubeBridgeHandlerRegisteredAndUnregister(org.openhab.binding.max.test.MaxBridgeHandlerOSGiTest)  Time elapsed: 6.887 sec

```

**Comment by kaikreuzer** [comment] 2016-03-28 12:10
>  I don't think current Oompf OH2 eclipse environment is very supportive of the groovy stuff

The Groovy tooling is [part of the IDE install](https://github.com/openhab/openhab-distro/blob/master/launch/openHAB2.setup#L2239), so what exactly are you missing?

**Comment by svilenvul** [comment] 2016-03-28 12:23
Actually I didn't have problems with the Oompf OH2 eclipse environment. 

But I think the Groovy Eclipse compiler can be added to a parent POM - e.g. [maybe here](https://github.com/openhab/openhab2-addons/blob/master/pom.xml).

Otherwise developers of new bindings will face the same problem.

**Comment by marcelrv** [comment] 2016-03-28 12:39
I was assuming there was a way in the IDE to run the test.

Maybe it is matter of configuration, but neither in my Oompf based environment in the MAX! binding, nor in e.g. the Hue binding I see a way to right-click the groovy file and say debug as... some test that won't directly fail. (it has the Junit test and the Junit plug-in test as available options, both fail )

Sofar I only saw these groovy tests working when doing the maven build

**Comment by svilenvul** [comment] 2016-03-28 13:03
> Maybe it is matter of configuration, but neither in my Oompf based environment in the MAX! binding, nor in e.g. the Hue binding I see a way to right-click the groovy file and say debug as... some test that won't directly fail. (it has the Junit test and the Junit plug-in test as available options, both fail )

Yes, you have to configure manually the bundles, that Eclipse will run in Equinox.

Choose the required bundles for your specific test (Run configurations -> Plugins -> Launch with: plug-ins selected below only), set up the their start level, set autostart to true for your Host-Bundle. Before running the test, choose "Validate plugins" and "Add Required Plug-ins" and you will have a running debug environment.

It can be tricky the first time, but do not be discouraged.
