### ISSUE TITLE
Accessing items in rules during startup

### ISSUE THREAD

**Issue by grzech1983** [openhab/openhab2#184] opened 2015-04-09 05:10 UTC
Hello,

I'm looking at switching to OH2 with my current configuration and one of things which I've noticed is error for accessing items in rules during OH2 startup. I'm using sample rules for irrigation from OH1 samples wiki:

https://code.google.com/p/openhab-samples/wiki/Rules

With item:

Switch  Irrigation_Master       "Irrigation Master"     <grass>

but during OH2 startup I see:

08:03:41.331 INFO  o.o.c.internal.CoreActivator[:55]- openHAB runtime has been started (v2.0.0, build 201503291351).
08:04:31.488 ERROR o.e.s.m.r.r.i.e.RuleEngineImpl[:274]- Error during the execution of startup rule 'Irrigation startup': The name 'Irrigation_Master' cannot be resolved to an item or type.

I have also other similar errors from other rules. Is this an issue or maybe something changed in rules configuration which needs to be applied to rule files?

My switch item is located in irrigation.items file located in OH2/conf/items

Regards

**Comment by kaikreuzer** [comment] 2015-04-10 20:19
Thanks for the report. I would like to treat this as a duplicate of https://github.com/openhab/openhab2/issues/76 as the same effect has been discussed there as well.

**Closed by kaikreuzer** 2015-04-10 20:19 UTC
