### ISSUE TITLE
Permanent Generation - Out of Memory errors

### ISSUE THREAD

**Issue by kgoderis** [openhab/openhab2#276] opened 2015-06-04 10:15 UTC
I hoped we would never come to this, but the day of (memory) doom has arrived

I have alpha2 running, with some bindings, and after a day or so I get a ton of the above related to an out of memory on the PermGen. I am in the processing of attaching jvisualm to my VM but it takes ages. I can this not yet say what is the problem here. I will also adjust the JVM startup parameters to increase the space allocated to the JVM but since nothing is specified, I guess the default value (16 MB?) is way too low. 

Some stats: 
14812 classes loaded in the perm gen, 6153 unloaded (this is huge!)
1460 threads, 2032 at peak, and 278K threads started (that last number I am not sure if it really started, thus also re-using threads in all the thread pools we have, or threads "created")

Hope to be able to post something more later on, the whole JVM is taking now about 1G of memory, and jvisualvm is struggling

**Comment by kgoderis** [comment] 2015-06-04 11:08
FYI, in my config, starting the OH runtime, and getting passed the .items parsing, yields me a PermGen of 135MB/84MB size/used alone, with 15000-ish classes loaded.

**Comment by kaikreuzer** [comment] 2015-06-04 21:19
> 1460 threads, 2032 at peak

You should definitely check where these threads are coming from - this seems to be your leak. Usually, openHAB should not exceed 100 threads (with the exception of some very short peaks when doing a UPnP scan), I would say. So something seems to create an abundance of them and thus eats your CPU & memory likewise.

**Comment by kaikreuzer** [comment] 2015-06-05 05:57
I just ran a test for > 8 hours with a few bindings active and all looks pretty stable. I guess you will have to find out, which of your bindings causes the problem as I am pretty sure it is not the runtime itself.
![visualvm](https://cloud.githubusercontent.com/assets/3244965/8000239/4e6f2d02-0b58-11e5-918c-1bb3f22a20f4.png)

**Comment by teichsta** [comment] 2015-06-05 09:05
very interesting CPU usage … are there any rules active on this system?

**Comment by kgoderis** [comment] 2015-06-05 11:20
Yes some but not a million either

**Comment by kgoderis** [comment] 2015-06-05 19:03
Did the same load testing over here, and did not get the problem (but I changed some -X parameters as well). PermGen is about 80-90MB in size. 

jupnp creates and awfull lot of threads!

**Comment by kaikreuzer** [comment] 2015-06-05 19:13
> jupnp creates and awfull lot of threads!

This depends on the number of devices that respond to UPnP searches - and your network is definitely at the top end of the expected ranges ;-)

**Comment by kaikreuzer** [comment] 2015-06-05 19:14
> jupnp creates and awfull lot of threads!

This depends on the number of devices that respond to UPnP searches - and your network is definitely at the top end of the expected ranges ;-)

**Comment by kaikreuzer** [comment] 2015-06-05 19:21
> jupnp creates and awfull lot of threads!

This depends on the number of devices that respond to UPnP searches - and your network is definitely at the top end of the expected ranges ;-)

**Comment by kaikreuzer** [comment] 2015-06-05 19:21
> jupnp creates and awfull lot of threads!

This depends on the number of devices that respond to UPnP searches - and your network is definitely at the top end of the expected ranges ;-)

**Comment by kgoderis** [comment] 2015-06-08 11:07
This is the situation after a few hours of running alpha2
The number of threads of jupnp is really huge - maybe we should investigate the jupnp lib a bit to reduce that number. The thread that is taking a lot of memory is related to the KNX binding

![vvm1](https://cloud.githubusercontent.com/assets/5459062/8033494/23f54e6a-0ddf-11e5-9048-117cb270e3e1.jpg)
![vvm2](https://cloud.githubusercontent.com/assets/5459062/8033495/2426314c-0ddf-11e5-94b1-a9adcd576c77.jpg)

**Comment by kaikreuzer** [comment] 2015-06-12 08:00
> The number of threads of jupnp is really huge - maybe we should investigate the jupnp lib a bit to reduce that number.

I guess you mean the number of started threads. Well, I once looked into this already. The problem is that any incoming upnp message must be handled, so a thread is opened for all of them, but they are very short-lived. Changing this behavior to an async processing of requests would probably mean to switch to Java NIO, which would be a major refactoring of jUPnP.

> The thread that is taking a lot of memory is related to the KNX binding

I guess this is the KNX 2.0 binding? Then I assume you are looking into it yourself already :-)

**Comment by kaikreuzer** [comment] 2015-06-12 08:01
Could we close this issue and create a more specific one, if you have some analysis results about KNX?

**Comment by kgoderis** [comment] 2015-06-12 11:03
well, one last thing:

I noticed that a lof of threads are of the Daemon Thread type, and a lot are ordinary Threads. I already had the case the JVM could not exit (after a necessary kill -9 on the JVM), leading to a full reboot of the host

I just wonder if should not make all threads of the Daemon type, enlarge the scheduler pool thread, and abandon all thread pools in the child classes. 

On KNX, that part of the code is copy/paste from OH1, I did not look into it yet but will do

**Comment by kaikreuzer** [comment] 2015-06-16 12:03
> I just wonder if should not make all threads of the Daemon type, enlarge the scheduler pool thread, and abandon all thread pools in the child classes.

Might make sense indeed. Having bindings uncontrolled creating threads is imho not a good thing.

**Closed** 2015-06-23 09:10 UTC

**Comment by kgoderis** [comment] 2015-06-30 12:22
Sorry to re-open/hijack this thread. 

I have been monitoring an OH alpha2-mid-june build and for some reason the number of threads spawned by the java binary creep upwards over time, until the JVM hits the "ulimit -a" of the OS. It seems that the LIFX underlying lib is really spawning a lot of Timer threads, and it seems that some of them keep lingering. But it could equally be something else. It is now running around 1100 threads constantly 

Anyways, proposal was to make the number of threads in the Google thread pool available to the Handlers a configurable parameter so that this can be reconfigured fast without having to recompile everything. With a larger number of bindings in a running config, this should be increased accordingly to give every binding a "fair" amount of CPU power.

**Comment by kaikreuzer** [comment] 2015-07-01 10:12
> It seems that the LIFX underlying lib is really spawning a lot of Timer threads, and it seems that some of them keep lingering.

I also think that the LIFX lib seems to have quite some issues. So my first suggestion would be to remove this binding and see if the number of active threads still continues to increase over time.

> Google thread pool

What is this? :-)

>  number of threads a configurable parameter

I agree. I was also thinking about some central class that manages the thread pools - this could then be the configurable service. Would you want to enter a bugzilla issue in ESH for this?
