### ISSUE TITLE
Events from Sonos are not braodcasted

### ISSUE THREAD

**Issue by wolter** [openhab/openhab2#98] opened 2015-01-02 16:25 UTC
Changing the volume on the Sonos device directly will not be reflected in the UI (seems there are no events broadcasted).

**Comment by kaikreuzer** [comment] 2015-01-02 16:30
This is a duplicate of #31. 
Is GENA event subscription working in general for you? I.e. do you get updates from tracks etc?

**Comment by kgoderis** [comment] 2015-01-04 11:29
Kai, did you find the time the yet to further test the GENA on your setup? Cfr our discussion last year, I am still unable to reproduce the issue in my setup (in eclipse that is, for sure, but I also think I did not encounter it in an 2.0Alpha test setup)

**Comment by kaikreuzer** [comment] 2015-01-04 20:30
Karel, I actually asked @wolter (a colleague) to further test GENA and to help you to come up with a reproducible scenario.

**Closed** 2015-01-19 16:32 UTC

**Comment by kaikreuzer** [comment] 2015-01-19 16:33
Good news Karel! I took the time to debug this further and noticed that the GENA callbacks happened on port 0 instead of 8080 - I was not able to get it working with the fix in jupnp. Will provide a new jupnp version to make it available in openHAB 2.

**Comment by kgoderis** [comment] 2015-01-19 17:43
Hue? I though we fixed that a long time ago. in https://github.com/JochenHiller/jupnp/commit/361937ea0f3fdea4393bbe573b9092ee57e65920 ?
Strangly enough I have that parameter set to 8080 and it seems to work for me. I also have org.jupnp:multicastResponsePort=0. It relates back to our discussion on ephemeral port numbers but I can't find it back

**Comment by kaikreuzer** [comment] 2015-01-19 19:05
That fixed it for the case that the callbacks were received through a dedicated server socket; but then I changed the callback to go through a servlet that registers on the OSGi HttpService - and from the code, this cannot really have worked so far. Never mind, now it also works for me, so there is no one left who complains ;-)
